#! /bin/bash
source /home/towshif/venv38/bin/activate

# virtualenv is now active.
# cd /home/towshif/code/python/pythonic

cd /home/towshif/code/python/pythonic/app_web/logically 
python EODUpdater.py

exit
