#!/usr/bin/env bash

cd /home/towshif/code/python/pythonic/


## This script compresses the database directory to a zip file 

# zip -qr database.zip database/ -x database/olddata/*

# Define date
d=$(date +%m%d%Y)
# echo "$d"
# echo "database_$d.zip"

# fname = "database_$d.zip"

zip -qr "backups/database_$d.zip" database/ -x database/olddata/*
